version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: casaos-filebrowser
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./data/database.db:/database.db
      - ./data/config/settings.json:/.filebrowser.json
      - ./shared:/srv
